version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable  # Image de base pour CircleCI
    steps:
      - checkout  # Récupérer le code source

      - setup_remote_docker  # Activer Docker dans CircleCI

      - run:
          name: Build Docker Image
          command: docker build -t my-app .

      - run:
          name: Run Docker Container
          command: docker run -d -p 8080:8080 --name my-app-container my-app

      - run:
          name: Run Tests
          command: docker exec my-app-container npm test  # Modifier si nécessaire

      - run:
          name: Clean Up
          command: docker stop my-app-container && docker rm my-app-container
