version: 2.1

jobs:
  build_and_run:
    docker:
      - image: node:14  # Utilisation de l'image officielle Node.js
    steps:
      - checkout  # Clone le repo
      - run:
          name: Installer les dépendances
          command: npm install
      - run:
          name: Lancer l'application
          command: npm start

workflows:
  version: 2
  build_and_run:
    jobs:
      - build_and_run
