version: 2.1

jobs:
  build_and_run:
    machine:
      image: circleci/classic:latest  # Utilisation d'une machine CircleCI
    steps:
      - checkout  # Clone le repo
      - run:
        name: Build Docker image
        command: docker build -t my-app-image .
      - run:
        name: Run Docker container
        command: docker run -d -p 8080:8080 my-app-image
      - run:
        name: test with curl
        command: curl -s http://localhost:8080

workflows:
  version: 2
  build_and_run:
    jobs:
      - build_and_run
